### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by boodaliboo** [Xahkarias/Evolved-Organs#49]
cant install pinions or glands is there any tech required or something no info on the workshop page about it

**Comment by jetharius** [comment]
is this on a vanilla race or a modded race?  Are you using any other mods?

**Comment by boodaliboo** [comment]
im using only the mod that adds the soldier, lizard and wolf men mod and by looking through the github it looks like there supported and i also use star wars the force and expanded prosthetics and organ engineering

**Comment by jetharius** [comment]
there is a lizardmen mod patch, wolfmen and soldier however are not supported to my knowledge, what are the mod names specifically? and upon which races are you encountering this issue?

**Comment by boodaliboo** [comment]
i have no way to check the races that i know of as they visually are identical and the mod is called xenohumans

**Comment by jetharius** [comment]
I cant seem to duplicate this issue.  I was able to install all the EvOrgan implants in the wolf/lizard/soldier/mate races added in xenomorphs.  The races are inherting the body part def of the humanlike def, Make sure you put xenomorphs before evolved organs in your load order and see if the issue persists in a new game.

**Comment by boodaliboo** [comment]
Sure I’ll test that soon

**Comment by jetharius** [comment]
I didn't think about this at the time but I am using the dev branch of evolved organs so there might be some incidental fix in the versions i cant remember off the top of my head.
